version: '3.8'

services:
  enterprise-demo:
    build: .
    ports:
      - "3000:3000"
      - "3002:3002"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped