version: '3.8'

services:
  design-system-mcp:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    healthcheck:
      test: ["CMD", "curl", "-f", "./mcp/design-system"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./cre8-wc-components.md:/app/cre8-wc-components.md:ro